apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehiclerental-2306203236-fe
  labels:
    app: vehiclerental-2306203236-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vehiclerental-2306203236-fe
  template:
    metadata:
      labels:
        app: vehiclerental-2306203236-fe
    spec:
      containers:
        - name: vehiclerental-2306203236-fe
          image: kadeksavitri/vehiclerental-2306203236-fe:REPLACE_ME_TAG
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi