apiVersion: v1
kind: Service
metadata:
  name: vehiclerental-2306203236-fe-service
spec:
  selector:
    app: vehiclerental-2306203236-fe
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80